---
name: 'Gradle Build Action'
description: 'Reusable GitHub Action for performing a gradle build or running a gradle task.'

inputs:
  gradle-cache-disabled:
    description: 'Caching is enabled by default. You can disable caching for the action using this parameter'
    required: false
    default: "false"
  gradle-cache-read-only:
    description: 'Configure read-only caching for the gradle-build-action'
    required: false
    default: ${{ github.ref != 'refs/heads/main' }}
  gradle-cache-write-only:
    description: 'Configure write-only caching for the gradle-build-action'
    required: false
    default: "false"

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
      with:
        node-version: 24
        check-latest: true
        cache: "yarn"
    - name: Set up JDK 21
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
      with:
        java-version: "21"
        distribution: "temurin"
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5
      with:
        add-job-summary: on-failure
        cache-disabled: ${{ inputs.gradle-cache-disabled }}
        cache-read-only: ${{ inputs.gradle-cache-read-only }}
        cache-write-only: ${{ inputs.gradle-cache-write-only }}
