name: Main

on:
  push:
    branches: [main]
  release:
    types: [created, published]

permissions:
  contents: write

jobs:
  gh-dependency-graph:
    name: Generate and Submit Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3